SELECT * FROM dba_scheduler_jobs WHERE job_name='MASTER_TABLE_JOB'

SELECT ERR_PROCEDURE, count(*) FROM 
EXPENSE_MANAGER.EM_MASTER_TABLE_ERROR_LOG
WHERE ERR_DATE>to_date('2018-08-06','YYYY-MM-DD')
GROUP BY ERR_PROCEDURE

SELECT * FROM EXPENSE_MANAGER.EM_MASTER_TABLE_ERROR_LOG WHERE ERR_DATE>to_date('2018-08-06','YYYY-MM-DD')